### ISSUE TITLE
Request: export gatherInfo and processField functions

### ISSUE THREAD

**Issue by bwhaley** [kelseyhightower/envconfig#131]
Thanks for writing envconfig!

I'd like to use envconfig with a wrapper library that will read config from the AWS SSM Parameter Store if they exist but otherwise pull from the environment. I'd like to reuse the logic in `gatherInfo()` and `processField()`. Any possibility of exporting those names? 

Actually, if these lines were changed, then `Process()` could have pluggable config sources. My code would end up just repeating `Process()` except for the env lookup.

https://github.com/kelseyhightower/envconfig/blob/dd1402a4d99de9ac2f396cd6fcb957bc2c695ec1/envconfig.go#L184-L191

**Comment by bwhaley** [comment]
Let me know if this change isn't something you'd like to implement for envconfig. The scope of envconfig is pretty well defined, after all - I could understand not wanting to support something like my wrapper library. I can always maintain a fork with the feature I want.

**Comment by teepark** [comment]
Thanks for acknowledging the well-defined scope 👍. I have to agree pluggable configuration sources aren't really in scope here.

A lot of requests (typically denied) have come up and basically amount to wanting access to the hard work put into this library of string parsing and struct filling. I think the best way to satisfy this kind of request would be splitting this into multiple packages, separating "string parsing -> struct filling" and "configuration from environment" (with the latter depending on the former).

Then rather than going full Frankenstein and tackling configuration sources as plugins/interfaces, people with this kind of use-case could just take dependencies on the string parsing and struct filling package and do their own thing.

I can't see myself putting in the time to do that re-org any time soon though, just floating the concept.
