### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by AlmogBaku** [kelseyhightower/envconfig#132]

**Comment by ivanovaleksey** [comment]
Maybe we could release a new version.
For instance, there was implemented [support for `url.Url`](https://github.com/kelseyhightower/envconfig/pull/101).
The latest release v1.3.0 was on 24 Jan 2017.

**Comment by Azuka** [comment]
@teepark, @kelseyhightower, would it be possible to tag the latest master as 1.4.0?

**Comment by marco-m** [comment]
@kelseyhightower , @teepark Could you please chime in?

**Comment by teepark** [comment]
Hi folks.

It's been a long time since I've made any time for envconfig, and I don't particularly see that changing much any time soon. So in a bit here I'll be stepping down as maintainer. Today I'm trying to clear out the backlog and merge/fix or at least comment on every issue and PR before I depart this maintainership entirely. This has already resulted in a `go.mod` file, and I expect I'll be cutting a release this weekend as well.

**Comment by marco-m** [comment]
Hello @teepark, thanks for answering and for clearing the backlog. I understand maintaining an open source project is hard. Thank you and all the maintainers for all the work ❤️
