### ISSUE TITLE
Unprefixed value is used if prefixed value is not available

### ISSUE THREAD

**Issue by FranGM** [kelseyhightower/envconfig#14]
Hi,

The following playground link should illustrate this issue: http://play.golang.org/p/XHSJ8ihZh-

If MYAPP_USER is not defined but USER is, the value of USER will be used instead. This seems to be a side effect of https://github.com/kelseyhightower/envconfig/pull/10 , in https://github.com/kelseyhightower/envconfig/blob/master/envconfig.go#L51 we use fieldName as key without actually checking if a struct tag was actually set.

I can submit a PR for this but want to make sure the current behaviour is not intentional and this is not just a documentation issue.

**Comment by FranGM** [comment]
Had to fix it for my project so ended up creating a pull request anyway: https://github.com/kelseyhightower/envconfig/pull/15

**Comment by rafaeljusto** [comment]
We still get this problem when adding a tag. For example, in the code bellow I expected to fill the `T.Thing` only when there's a `MYAPP_THING` environment variable. But it accepts a `THING` environment variable.

```go
package main

import (
	"fmt"
	"os"

	"github.com/kelseyhightower/envconfig"
)

type T struct {
	Thing string `envconfig:"thing"`
}

func main() {
	os.Setenv("THING", "123")
	t := T{}
	envconfig.Process("myapp", &t)
	fmt.Printf("This should be empty: %v", t.Thing)
}
```

This problem was introduced by the `varInfo.Alt` attribute in PR #61. We use the `Alt` whenever the `varInfo.Key` [wasn't found](https://github.com/kelseyhightower/envconfig/blob/master/envconfig.go#L157), but `Alt` doesn't have the prefix in it. Is there any reason to why we don't add prefix to `varInfo.Alt`?

**Comment by davidkbainbridge** [comment]
@rafaeljusto Attempting to think back, so please be patient ...

As I recall when I was doing the update the `alt` specification was documented as not using the prefix, but instead being the directly used for looking up a value. I believe, but haven't verified, that this is how the tests cases were designed as well.

**Comment by rafaeljusto** [comment]
You are right! This behavior is much older than your PR. It was introduced in the commit fab02b324e628c39a622baa3b3a5c71e94aadfdd and is also documented in README:

> If envconfig can't find an environment variable in the form PREFIX_MYVAR, and there is a struct tag defined, it will try to populate your variable with an environment variable that directly matches the envconfig tag in your struct definition

Thanks!
