### ISSUE TITLE
Extend Usage to print values

### ISSUE THREAD

**Issue by AlekSi** [kelseyhightower/envconfig#77]
This way `Usage()` can be used after processing to print applied configuration as a better-looking alternative to `fmt.Printf("%+v\n", config)`.

**Comment by teepark** [comment]
This seems like a debugging use case? Applications may reasonably need to:
1. parse configuration from the environment
2. print helpful output documenting supported environment vars and their types

I'm trying to wrap my head around the need for this or find precedent anywhere else. It would be like if `someapp -t -a -N 2 -h` printed help output informing the user that they activated the "t" and "a" flags, and that the "N" value is 2.

**Comment by relistan** [comment]
I think @AlekSi might be trying to solve the problem of "What the heck actually got applied from the env vars I passed" because it can be challenging to figure out which were actually picked up. I wrote a thing which we use to solve that: https://github.com/relistan/rubberneck

Configure your app with envconfig, and then on startup have it dump the config it's running from to the logs. You could also do this from a CLI switch if needed.

**Comment by teepark** [comment]
@relistan that package looks great! I agree it's not really the job of envconfig -- I'll be pointing people to your package next time this comes up.

**Comment by relistan** [comment]
Thanks @teepark!
