### ISSUE TITLE
Cut a new tagged release?

### ISSUE THREAD

**Issue by carloscarnero** [kelseyhightower/envconfig#81]
The [releases page](https://github.com/kelseyhightower/envconfig/releases) list [1.3.0](https://github.com/kelseyhightower/envconfig/releases/tag/v1.3.0) as the latest. Is there merit to cut a new release (maybe minor, like 1.3.1) since there have been [three changes](https://github.com/kelseyhightower/envconfig/compare/v1.3.0...master)?

**Comment by teepark** [comment]
Really it's just [the one change](https://github.com/kelseyhightower/envconfig/commit/8bf4bbfc795e2c7c8a5ea47b707453ed019e2ad4) (ci details and badges don't count).

I believe it should be a minor release (to 1.4.0) because the new valid bool values are user-facing API, but it's pretty inconsequential so I'd prefer to wait.
