### ISSUE TITLE
Exporting gatherInfo()

### ISSUE THREAD

**Issue by dewrich** [kelseyhightower/envconfig#97]
Would be nice to have this available so that I could build a command line `Usage` for the Environment Variables that are available to override.

For example, you could build a mapping of the env vars defined in your struct to some Usage doc that describes the fields individually.

https://github.com/kelseyhightower/envconfig/blob/462fda1f11d8cad3660e52737b8beefd27acfb3f/envconfig.go#L57

**Comment by teepark** [comment]
Hi @dewrich! Envconfig is really targeted at doing a specific job rather than being an environment variable swiss-army knife. IMO it's better to keep the API surface low rather than exposing internals to cover every possible use-case.

That being said, your example of building a usage doc is already possible with the `Usage` family of functions: [`Usage`](https://godoc.org/github.com/kelseyhightower/envconfig#Usage), [`Usagef`](https://godoc.org/github.com/kelseyhightower/envconfig#Usagef), or [`Usaget`](https://godoc.org/github.com/kelseyhightower/envconfig#Usaget) for maximum control.
